Feat/11/pagination etc
AdrianKokot/put-reunice-platform pull request #12
Opened 2023-08-02 16:02 UTC by WiktorSzymanski

2023-08-19 08:16 UTC, AdrianKokot requested changes

2023-08-19 08:16 UTC, AdrianKokot commented on backend/src/main/java/com/example/cms/user/UserSpecification.java
> +    public Predicate toPredicate(Root<User> root, CriteriaQuery<?> query, CriteriaBuilder criteriaBuilder) {
Kluczowe przy użytkownikach wydaje się jeszcze dodanie kryterium `univeristyId_eq`, które sprawdzi, czy użytkownik jest przypisany do uniwersytetu o podanym id

2023-08-19 08:16 UTC, AdrianKokot commented on docker-compose.yml
Ten plik do synchronizacji z `main`

2023-08-19 08:16 UTC, AdrianKokot commented on backend/src/main/resources/application.yml
Ten plik do synchronizacji z `main`

2023-08-19 08:16 UTC, AdrianKokot commented on frontend/Dockerfile
Ten plik do synchronizacji z `main`

2023-08-19 08:16 UTC, AdrianKokot commented on frontend/default.conf
Ten plik do synchronizacji z `main`

2023-08-19 08:16 UTC, AdrianKokot commented on frontend/proxy.conf.json
Ten plik do synchronizacji z `main`

2023-08-22 16:48 UTC, WiktorSzymanski commented on backend/src/main/java/com/example/cms/user/UserSpecification.java
> +    public Predicate toPredicate(Root<User> root, CriteriaQuery<?> query, CriteriaBuilder criteriaBuilder) {
Po zmianach enrolledUniversities_eq spełnia tę rolę

2023-08-22 17:14 UTC, AdrianKokot approved these changes

2023-08-22 17:45 UTC, merged