Feat/email service
AdrianKokot/put-reunice-platform pull request #17
Opened 2023-08-11 20:34 UTC by BartoszDolata

2023-08-11 21:05 UTC, BartoszDolata commented
Something went wrong with passing variables from .env.example. Tested on docker and email was sent :(

2023-08-12 08:39 UTC, AdrianKokot requested changes

2023-08-12 08:39 UTC, AdrianKokot commented on backend/src/main/java/com/example/cms/email/EmailSendingService.java
> +        message.setFrom("test@mailpit");
This should use `SMTP_USERNAME` env variable

2023-08-12 08:39 UTC, AdrianKokot commented on backend/pom.xml
>  		<resources>
This section with resources can be deleted as angular application was moved to separate directory and is no longer inside spring project

2023-08-12 08:39 UTC, AdrianKokot commented on backend/Dockerfile
> +ARG SMTP_SERVER
This should not be needed, env variables are passed automatically to dockerfile during build, see [Dockerfile in root](https://github.com/AdrianKokot/put-reunice-platform/blob/main/Dockerfile), where I removed all `ARG ...` and `ENV ...` and environment variables are still recognized properly.

2023-08-12 08:41 UTC, AdrianKokot commented
> Something went wrong with passing variables from .env.example. Tested on docker and email was sent :(

Docker compose automatically searches for `.env` file, so either you should copy `.env.example` content to `.env` locally (it's marked in .gitignore to not push db passwords etc to remote) or add `--env-file` parameter when running docker, ex. `docker compose up -d --env-file .env.example`

2023-08-16 10:52 UTC, AdrianKokot approved these changes

2023-08-16 14:27 UTC, merged