🔎 Search bar yay! 🔎
AdrianKokot/put-reunice-platform pull request #66
Opened 2023-09-09 20:56 UTC by mudziok

This code is bugged - if you hover datalist inside the sidebar it closes the sidebar. Im pretty sure this is the issue of ActiveZone as the datalist is portalled somewhere else in the dom.

After like an hour of trying I concede defeat as the syntax of the activezone stuff is so cryptic that I simply cannot figure this out XD

2023-09-09 20:56 UTC, mudziok commented
Ofc we'll have to change this once the algolia like search is in place

2023-09-14 18:17 UTC, AdrianKokot approved these changes
As we now have something useful in the searchbar, I think the menu button should be always visible, because user might want to search something before entering any university's page.

Create issue with the bug you mentioned, I'll try to fix it.

2023-09-16 13:40 UTC, AdrianKokot requested changes

2023-09-16 13:40 UTC, AdrianKokot commented on frontend/modules/shared/ui/src/lib/layout/search/search.component.html
To resolve #69 you can add two lines:

```html
<tui-input
   #input <!-- This -->
>
<a
  (click)="input.open = false" <!-- And this -->

```

2023-09-16 13:40 UTC, AdrianKokot commented on frontend/modules/shared/ui/src/lib/layout/search/search.component.html
And to resolve #70 you can move template binding from `*tuiLet` to `*ngFor`:

```html
<tui-input
  *tuiLet="results$ | async as results" <!-- Remove this line --->

<a
  *ngFor="let page of results$ | async" <!-- And use async pipe here --->
```

2023-09-16 16:49 UTC, mudziok commented on frontend/modules/shared/ui/src/lib/layout/search/search.component.html
Thank you

2023-09-16 16:51 UTC, mudziok commented on frontend/modules/shared/ui/src/lib/layout/search/search.component.html
🤯

2023-09-16 18:03 UTC, AdrianKokot approved these changes

2023-09-16 18:53 UTC, merged