feat: option to assign somone to page
AdrianKokot/put-reunice-platform pull request #92
Opened 2023-09-30 15:24 UTC by WiktorSzymanski

Closes #91

2023-10-02 14:49 UTC, BartoszDolata approved these changes

2023-10-05 11:08 UTC, AdrianKokot requested changes

2023-10-05 11:08 UTC, AdrianKokot commented on backend/src/main/java/com/example/cms/page/PageController.java
> +    ResponseEntity<Void> addPageHandlers(@PathVariable long id, @RequestBody List<Long> pageHandlers) {
Proszę o dodanie `List<Long> contactRequestHandlers` do `PageEditFormDto` i przypisywanie ich z metody do edycji `Page`, wtedy już z poziomu frontu też będzie działać bo na to jest przygotowany formularz

2023-10-08 10:35 UTC, AdrianKokot approved these changes

2023-10-08 14:39 UTC, merged